#!/usr/bin/env bash
# install.sh — one-time bootstrap of mes-testing-pg VM
#
# Runs AFTER `gcloud compute instances create mes-testing-pg ...` and the
# new VM is reachable. Idempotent: safe to re-run.
#
# What it does (in order):
#   1. apt update + install system deps (git, python3-venv, postgresql-client)
#   2. Download Cloud SQL Auth Proxy binary, install systemd unit
#   3. Create cloudsqlproxy + mes service users
#   4. Clone MESv1.0 repo to /opt/mes, install Python venv + deps
#   5. Pull Postgres password from Secret Manager into /etc/mes-pg.env
#   6. Install pg_dump backup script + cron
#
# This script is intended to be uploaded to the VM and run as root:
#   gcloud compute scp install.sh anthony@mes-testing-pg:/tmp/ --zone=us-central1-a
#   gcloud compute ssh anthony@mes-testing-pg --zone=us-central1-a \
#       --command="sudo bash /tmp/install.sh"

set -euo pipefail

GCP_PROJECT="superb-metric-492315-r5"
PG_INSTANCE="mes-pg-staging"
PG_SECRET_NAME="mes-pg-app-password"
PG_APP_USER="mes_app"
PG_DB_NAME="mes"
MES_REPO="https://github.com/MSPlastics/MESv1.0.git"
MES_BRANCH="lanes-per-master-fix"

# ---------------------------------------------------------------------------
echo "==> [1/6] apt + system deps"
apt-get update -qq
# pycairo (a transitive dep of xhtml2pdf via reportlab) builds from source
# during pip install and requires libcairo2-dev + pkg-config. The existing
# mes-testing VM has these installed (verified 2026-05-24); mirror them
# so the MES pip install succeeds on a fresh box.
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    git python3-venv python3-pip python3-dev \
    postgresql-client curl ca-certificates jq \
    pkg-config libcairo2-dev libpixman-1-dev \
    build-essential

# ---------------------------------------------------------------------------
echo "==> [2/6] Cloud SQL Auth Proxy"
# Real /home/cloudsqlproxy so the proxy's stdlib home-dir lookups work.
# (See cloud-sql-proxy.service for why we can't redirect via HOME env var.)
id -u cloudsqlproxy &>/dev/null || useradd --system --shell /bin/false \
    --home-dir /home/cloudsqlproxy --create-home cloudsqlproxy
install -d -o cloudsqlproxy -g cloudsqlproxy /opt/cloud-sql-proxy
# Pre-create the config + secureConnect dirs the proxy reads on startup
install -d -m 0750 -o cloudsqlproxy -g cloudsqlproxy /home/cloudsqlproxy/.config /home/cloudsqlproxy/.config/gcloud
install -d -m 0750 -o cloudsqlproxy -g cloudsqlproxy /home/cloudsqlproxy/.secureConnect

if [[ ! -x /opt/cloud-sql-proxy/cloud-sql-proxy ]]; then
    curl -sSLo /opt/cloud-sql-proxy/cloud-sql-proxy \
        "https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.13.0/cloud-sql-proxy.linux.amd64"
    chmod +x /opt/cloud-sql-proxy/cloud-sql-proxy
    chown cloudsqlproxy:cloudsqlproxy /opt/cloud-sql-proxy/cloud-sql-proxy
fi

# Install systemd unit (uploaded alongside this script)
install -m 0644 /tmp/cloud-sql-proxy.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable --now cloud-sql-proxy.service
sleep 3

# ---------------------------------------------------------------------------
echo "==> [3/6] /etc/mes-pg.env from Secret Manager"
PG_PASSWORD=$(gcloud secrets versions access latest --secret="$PG_SECRET_NAME" --project="$GCP_PROJECT")
umask 077
cat > /etc/mes-pg.env <<EOF
# MES PostgreSQL connection — sourced by mes.service
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Cloud SQL Auth Proxy listens on 127.0.0.1:5432 — see cloud-sql-proxy.service
DATABASE_URL=postgresql+psycopg://${PG_APP_USER}:${PG_PASSWORD}@127.0.0.1:5432/${PG_DB_NAME}
EOF
chown root:root /etc/mes-pg.env
chmod 0600 /etc/mes-pg.env
unset PG_PASSWORD
umask 022

# Smoke test the connection via the proxy
PGPASSWORD=$(gcloud secrets versions access latest --secret="$PG_SECRET_NAME" --project="$GCP_PROJECT") \
    psql -h 127.0.0.1 -U "$PG_APP_USER" -d "$PG_DB_NAME" -c "SELECT version()" >/dev/null
echo "    proxy + auth + db OK"

# ---------------------------------------------------------------------------
echo "==> [4/6] /opt/mes — clone + venv + deps"
if [[ ! -d /opt/mes/.git ]]; then
    git clone --branch "$MES_BRANCH" "$MES_REPO" /opt/mes
fi
cd /opt/mes
git fetch --quiet origin
git checkout "$MES_BRANCH"
git pull --ff-only origin "$MES_BRANCH"

if [[ ! -d /opt/mes/venv ]]; then
    python3 -m venv /opt/mes/venv
fi
/opt/mes/venv/bin/pip install --quiet --upgrade pip
/opt/mes/venv/bin/pip install --quiet -r /opt/mes/requirements.txt
/opt/mes/venv/bin/pip install --quiet 'psycopg[binary]>=3,<4'

# ---------------------------------------------------------------------------
echo "==> [5/6] backups: pg_dump cron -> gs://msp-mes-backups/postgres/"
install -m 0755 /tmp/backup_postgres.sh /opt/cloud-sql-proxy/backup_postgres.sh
# Cron every 15 minutes, mirroring the existing SQLite backup cadence
cat > /etc/cron.d/mes-pg-backup <<'EOF'
# MES PostgreSQL backup -> GCS, every 15 minutes
*/15 * * * * cloudsqlproxy /opt/cloud-sql-proxy/backup_postgres.sh > /var/log/mes-pg-backup.log 2>&1
EOF
chmod 0644 /etc/cron.d/mes-pg-backup
touch /var/log/mes-pg-backup.log
chown cloudsqlproxy:cloudsqlproxy /var/log/mes-pg-backup.log

# ---------------------------------------------------------------------------
echo "==> [6/6] done"
echo
systemctl is-active cloud-sql-proxy.service && echo "  cloud-sql-proxy: active"
echo "  /opt/mes: $(cd /opt/mes && git rev-parse --short HEAD) on $(cd /opt/mes && git branch --show-current)"
echo "  /etc/mes-pg.env: present (mode $(stat -c %a /etc/mes-pg.env))"
echo
echo "NEXT (manual):"
echo "  - Run schema bootstrap: /opt/mes/venv/bin/python -c 'from db_models import init_db; init_db()'"
echo "    (this calls Base.metadata.create_all() against the Postgres at DATABASE_URL)"
echo "  - Verify via: psql ... -c '\\dt' to see all tables"
echo "  - Then proceed to Phase 3 bulk load: sqlite_to_pg_migrate.py"
